ALTER TABLE users ADD COLUMN profile_type VARCHAR(50);
ALTER TABLE users ADD COLUMN degree VARCHAR(100);
ALTER TABLE users ADD COLUMN branch VARCHAR(100);
ALTER TABLE users ADD COLUMN study_year VARCHAR(50);
